#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# source config files

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set typematic delay [rate] -- default 660ms held, 25Hz repeat rate
xset r rate 300 50

# make sure DISPLAY is set right
systemctl --user import-environment DISPLAY

# statusbar loop
while true; do
   xsetroot -name "$(date +"%a, %D | %I:%M %p")"
   sleep 2s
done &

# start user programs 
dunst &
udiskie  &
startdwm
