#!/bin/zsh

# zsh configuration. Runs for interactive shells.

# performance debugging start
# start=$(date "+%s.%N")
# zmodload zsh/zprof

# ZSH settings
ZSH_THEME="zeta"
DISABLE_AUTO_UPDATE="true"
ZSH_COMPDUMP="${XDG_CACHE_HOME}/zsh/zcompdump-${ZSH_VERSION}"
plugin=()

# make sure completion list is loaded before anything else
zmodload zsh/complist

# Source ZSH frameworks
source $ZSH/oh-my-zsh.sh

# Source regular shellrc file
source "${XDG_CONFIG_HOME}/shell/shellrc"

# zsh theming
export zeta="λ"

# source plugins
fpath=("${XDG_CONFIG_HOME}/zsh/plugins" $fpath)

# extra completions
fpath=("${XDG_CONFIG_HOME}/zsh/plugins/zsh-completions/src" $fpath)

# vim related
bindkey -v 
KEYTIMEOUT=1
autoload -Uz cursor_mode; cursor_mode
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# syntax highlighting, should be at end
source "${XDG_CONFIG_HOME}/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# performance debugging end
# end=$(date "+%s.%N")
# date -u -d "0 $end sec - $start sec" +"%H:%M:%S.%N"

