#!/bin/zsh

# Generic shellrc file, runs for interactive shells.

# History settings
HISTCONTROL=ignoreboth # don't put duplicate lines or lines starting with space in the history.
HISTSIZE=50000

source "${XDG_DATA_HOME}/apparish/bourne-apparish"
source "${XDG_CONFIG_HOME}/shell/aliases"

# Override bm to allow for encrypted chezmoi file
function bm() {
	apparishbm "$1"
	chezmoi add --encrypt "${XDG_DATA_HOME}/apparish/apparixrc"
}

# Mkdir and move in one command
function md() { mkdir -p "$1" && cd "$1" ; }

# vi
set -o vi

# fzf
[ -f "/usr/share/fzf/key-bindings.zsh" ] && source "/usr/share/fzf/key-bindings.zsh"
[ -f "/usr/share/fzf/completion.zsh" ] && source "/usr/share/fzf/completion.zsh"

# broot
[ -f "${XDG_CONFIG_HOME}/broot/launcher/bash/br" ] && source "${XDG_CONFIG_HOME}/broot/launcher/bash/br"

# mcfly
[ -f "/usr/share/doc/mcfly/mcfly.zsh" ] && eval "$(mcfly init zsh)"
