---
style:
  tag:
    color: cyan
    width_percentage: 26
    min_width: 20
  comment:
    color: magenta
    width_percentage: 42
    min_width: 45
  snippet:
    color: white

finder:
  command: fzf

search:
  tags: ","

shell:
  command: zsh
