[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#54ced6"
green = "#9ec400"
magenta = "#b77ee0"
red = "#ff3334"
white = "#eaeaea"
yellow = "#e7c547"

[colors.cursor]
cursor = "#ffffff"
text = "#191b1d"

[colors.dim]
black = "#131415"
blue = "#556a7d"
cyan = "#5b7d78"
green = "#777c44"
magenta = "#75617b"
red = "#864343"
white = "#828482"
yellow = "#9e824c"

[colors.hints.end]
background = "#191b1d"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#191b1d"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#191b1d"
blue = "#81a2be"
cyan = "#70c0ba"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#e6c547"

[colors.primary]
background = "#191b1d"
foreground = "#c5c8c6"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

# [colors.search.footer_bar]
# background = "#c5c8c6"
# foreground = "#191b1d"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
